-- CreateTable
CREATE TABLE "_ENROLLED_IN" (
    "A" INTEGER NOT NULL,
    "B" INTEGER NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "_ENROLLED_IN_AB_unique" ON "_ENROLLED_IN"("A", "B");

-- CreateIndex
CREATE INDEX "_ENROLLED_IN_B_index" ON "_ENROLLED_IN"("B");

-- AddForeignKey
ALTER TABLE "_ENROLLED_IN" ADD CONSTRAINT "_ENROLLED_IN_A_fkey" FOREIGN KEY ("A") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_ENROLLED_IN" ADD CONSTRAINT "_ENROLLED_IN_B_fkey" FOREIGN KEY ("B") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
